name: 'Kickoff Build in App Center CI'
description: 'This action starts building a given branch in App Center'
inputs:
  appcenter-token:
    description: 'Value of your App Center token'
    required: true
  project-id:
    description: 'Name of your project ({{org/project_name}})'
    required: true
  branch:
    description: 'Name of your branch to be built'
    required: true
runs:
  using: 'node12'
  main: 'index.js'